### ISSUE TITLE
Can't use this module because of error:

### ISSUE THREAD

**Issue by achenchik** [hubot-scripts/hubot-bitbucket-pr#11]
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:  TypeError: Cannot read property 'display_name' of undefined 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at SlackPullRequestEvent.PullRequestEvent (/app/node_modules/hubot-bitbucket-pr/src/bitbucket-pr.coffee:49:5, <js>:51:35) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at new SlackPullRequestEvent (/app/node_modules/hubot-bitbucket-pr/src/bitbucket-pr.coffee:171:3, <js>:183:58) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at /app/node_modules/hubot-bitbucket-pr/src/bitbucket-pr.coffee:361:7, <js>:388:17 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at callbacks (/app/node_modules/hubot/node_modules/express/lib/router/index.js:164:37) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at param (/app/node_modules/hubot/node_modules/express/lib/router/index.js:138:11) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at pass (/app/node_modules/hubot/node_modules/express/lib/router/index.js:145:5) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at Router._dispatch (/app/node_modules/hubot/node_modules/express/lib/router/index.js:173:5) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at Object.router (/app/node_modules/hubot/node_modules/express/lib/router/index.js:33:10) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at next (/app/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:174:15) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at Object.multipart [as handle] (/app/node_modules/hubot/node_modules/connect-multiparty/index.js:42:27) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at next (/app/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:174:15) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at Object.urlencodedParser [as handle] (/app/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/urlencoded.js:81:44) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at next (/app/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:174:15) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at /app/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/read.js:121:5 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at invokeCallback (/app/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:262:16) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at done (/app/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:251:7) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at IncomingMessage.onEnd (/app/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:308:7) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at IncomingMessage.emit (events.js:92:17) 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at _stream_readable.js:944:16 
> Apr 25 06:13:46 titanium-hubot-for-slack app/web.1:    at process._tickCallback (node.js:458:13)

**Comment by achenchik** [comment]
Any ideas?

**Comment by achenchik** [comment]
my bad, was using wrong type of bitbucket hooks
